# Generated by Django 3.2.23 on 2023-11-29 14:58

from django.db import migrations, models
import profiles_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='image_saved',
            field=models.FileField(blank=True, default=None, null=True, upload_to=profiles_api.models.get_upload_path),
        ),
    ]
